apiVersion: harness.io/v1
kind: Workflow
type: template
identifier: test_workflow_remote_entity_qa
name: Test Workflow Remote Entity QA
owner: user:account/vigneswara.mh@harness.io
spec:
  output:
    links:
    - title: Pipeline Details
      url: ${{ steps.trigger.output.PipelineUrl }}
  lifecycle: production
  parameters:
  - title: Service Details
    required:
    - service_name
    properties:
      token:
        title: Harness Token
        type: string
        ui:widget: password
        ui:field: HarnessAuthToken
      service_name:
        title: Service Name
        type: string
        description: Mention the project name
  steps:
  - id: trigger
    name: Creating your appication
    action: trigger:harness-custom-pipeline
    input:
      url:
      - Harness Pipeline URL
      inputset:
        service_name: ${{ parameters.service_name }}
      apikey: ${{ parameters.token }}
  ownedBy:
  - user:account/vigneswara.mh@harness.io
metadata:
  description: Test Workflow Remote Entity QA
  tags:
  - spotify
  - rest
  - store
