apiVersion: harness.io/v1
kind: Component
type: website
identifier: test_import_remote_entity_qa
name: Test Import Remote Entity QA
owner: user:account/vigneswara.mh@harness.io
spec:
  lifecycle: production
  ownedBy:
  - user:account/vigneswara.mh@harness.io
metadata:
  description: Test Import Remote Entity QA
  tags:
  - rest
  - store
