---
kind: "Component"
spec:
  type: "Service"
  lifecycle: "production"
  owner: "idpui"
  system: "IDP_UI"
apiVersion: "backstage.io/v1alpha1"
metadata:
  name: "idp-app-public"
  tags: [javascript]
  description: IDP microfrontend which has both Backstage UI and Backend components
  annotations:
    harness.io/cd-serviceId: "idp"
    harness.io/ci-pipelineIds: Build_IDP_UI_App
    harness.io/project-url: "https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/ci/orgs/default/projects/IDP_UI/dashboard"
    harness.io/project-url-stage: https://stage.harness.io/ng/account/wFHXHD0RRQWoO8tIZT5YVw/cd/orgs/Harness/projects/Operations/deployments
    harness.io/projects-stage: RELEASEBUILDS,Operations
    harness.io/ci-pipelineIds-stage: IDPUICutBranch,IDPUIBuildRelease
    jira/project-key: IDP
    github.com/project-slug: harness/harness-idp
    backstage.io/source-location: 'url:https://github.com/harness/harness-idp/tree/main'
    backstage.io/techdocs-ref: 'url:https://github.com/harness/harness-idp/tree/docs'
    pagerduty.com/service-id: PT5ED69
