apiVersion: harness.io/v1
kind: Component
type: sample_component
identifier: dependencyOfStager_1_0_0
name: dependencyOf Stager 1.0.0
owner: group:account/_account_all_users
spec:
  lifecycle: example
  dependsOn:
    - component:account/stager_1_0_0
metadata:
  description: A dependency of Stager.
  tags:
  - pypi
  - python
  - has-dependency
