apiVersion: harness.io/v1
kind: Component
type: service
identifier: Test_Catalog_Race_Condition
name: Test Catalog Race Condition
owner: user:account/vigneswara.mh@harness.io
spec:
  lifecycle: production
metadata:
  description: Test Catalog Race Condition rzjR8UyZTpOAd6SLDfdBuw
  tags:
  - transaction
  - java
