apiVersion: harness.io/v1
kind: Component
type: service
identifier: test_catalog_remote1
name: Test Catalog remote1
owner: user:account/vigneswara.mh@harness.io
spec:
  lifecycle: production
metadata:
  description: Description added
  tags:
  - java
  - spotify
  - rest
