apiVersion: harness.io/v1
kind: Component
type: service
identifier: artistlookup_setup
name: artist-lookup
owner: team-a
orgIdentifier: testautoidp
projectIdentifier: testautoidp
spec:
  lifecycle: experimental
  dependsOn:
  - resource:artists-db
  apiConsumedBy:
  - component:www-artist
metadata:
  description: Artist Lookup
  annotations:
    backstage.io/linguist: https://github.com/backstage/backstage/tree/master/plugins/playlist
  links:
  - url: https://example.com/user
    title: Examples Users
    icon: user
  - url: https://example.com/group
    title: Example Group
    icon: group
  - url: https://example.com/cloud
    title: Link with Cloud Icon
    icon: cloud
  - url: https://example.com/dashboard
    title: Dashboard
    icon: dashboard
  - url: https://example.com/help
    title: Support
    icon: help
  - url: https://example.com/web
    title: Website
    icon: web
  - url: https://example.com/alert
    title: Alerts
    icon: alert
  tags:
  - java
  - data
