apiVersion: harness.io/v1
kind: Component
type: component
identifier: Test_Feature_Branch_Devspace
name: Test Feature Branch - Devspace
owner: user:account/vigneswara.mh@gmail.com
spec:
  lifecycle: experimental
metadata:
  tags:
  - spotify
  - java
  - mqtt
